### ISSUE TITLE
AGAT compatible with Perl 5.36 ?

### ISSUE THREAD

**Issue by eylenth** [NBISweden/AGAT#392]
**Describe the bug**
We are trying to run AGAT which is built with Perl 5.36 and more recent Perl packages, but we are getting `Undefined subroutine` error messages.
We did the same tests with AGAT(same version), which is built with Perl 5.32, where we are getting the expected output.

**General (please complete the following information):**
- AGAT version 1.2.0/1.1.0
- AGAT installation: Manual/EasyBuild
- OS: RedHat 7.9

**To Reproduce**
```
 $ agat_convert_sp_gxf2gxf.pl --gff 8_test.gff
Using standard /tools/eb/software/AGAT/1.1.0-GCC-12.2.0/lib/perl5/site_perl/5.36.0/auto/share/dist/AGAT/config.yaml file
Undefined subroutine &main::prepare_gffout called at /tools/eb/software/AGAT/1.1.0-GCC-12.2.0/bin/agat_convert_sp_gxf2gxf.pl line 47.
 $ agat_sp_statistics.pl --gff 8_test.gff -o stats.txt
Using standard /tools/eb/software/AGAT/1.1.0-GCC-12.2.0/lib/perl5/site_perl/5.36.0/auto/share/dist/AGAT/config.yaml file
Undefined subroutine &main::prepare_fileout called at /tools/eb/software/AGAT/1.1.0-GCC-12.2.0/bin/agat_sp_statistics.pl line 50.
```

**Expected behavior**
A lot of output related that the job is finished.

**Additional context**
EasyBuild is used to build AGAT from source:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/a/AGAT/AGAT-1.1.0-GCC-12.2.0.eb

**Comment by Juke34** [comment]
It should be compatible with 5.36 yes. 
I think it is just because no output file that was provided. (If I remember well in version 1.1.0 providing an output was mandatory ). It has been fixed in next release.

**Comment by eylenth** [comment]
hi @Juke34 

It seems that this issue is still not solved with the latest release. 
I have built AGAT with the latest commit: bea962b

**Comment by Juke34** [comment]
Maybe same problem as here: https://github.com/NBISweden/AGAT/issues/424#issuecomment-1942917802

I have to figure out how easy build works. You mean just changing the perl version from 5.32 to 5.36 make it breaks?

**Comment by eylenth** [comment]
@Juke34 
Yes indeed.
Working fine with Perl 5.32
Not working anymore with Perl 5.36

**Comment by EXGDT** [comment]
> @Juke34 Yes indeed. Working fine with Perl 5.32 Not working anymore with Perl 5.36

I encountered the same issue with Perl 5.38.
It was resolved after I downgraded from Perl 5.38 to 5.32.

**Comment by Juke34** [comment]
Interesting, thank you for the feedbacks

**Comment by boegel** [comment]
Are there any updates on figuring this out?

We're still getting reports with the problem with AGAT 1.4.0...

**Comment by Juke34** [comment]
No update sorry

**Comment by Juke34** [comment]
Now fixed in master branch via PR #509 #509

**Comment by eylenth** [comment]
hi @Juke34 
Thanks for the patch.
It works fine now.
